### ISSUE TITLE
Make `beeware-ci` package public

### ISSUE THREAD

**Issue by rmartin16** [beeware/.github#101]
### Describe the bug

The caching [package](https://github.com/beeware/.github/pkgs/container/beeware-ci) `beeware-ci` introduced via #99 needs to be public; it is currently private.

As a private package, only blessed GITHUB_TOKENs are allowed access as made evident by [CI](https://github.com/beeware/briefcase/actions/runs/8033834495/job/21944797188?pr=1666#step:21:79) for beeware/briefcase#1666.

### Steps to reproduce

Run CI for a PR from a non-beeware org member.

### Expected behavior

Caching image is available and pulled for CI runs.

### Environment

CI

**Comment by freakboy3742** [comment]
Is read permission sufficient, or do the other repos need write access as well?

**Comment by freakboy3742** [comment]
I've added READ permissions for all the repos that I think need it (briefcase, briefcase template repos, and Python-Apple-support and Python-support-testbed); if I've missed any, let me know.

**Comment by freakboy3742** [comment]
Also - how on earth do you navigate to the packages list without the magic URL in the ticket? I can see a bunch of Github documentation that says "just click on the `Packages` link"... but damned if I can find that link anywhere - it's definitely not where the screenshots say it is.

**Comment by rmartin16** [comment]
Right now, its any repo that runs `app-build-verify` for Linux System or AppImage builds will need read access:
```
briefcase/.github/workflows/ci.yml:    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
briefcase-linux-appimage-template/.github/workflows/ci.yml:    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
briefcase-linux-system-template/.github/workflows/ci.yml:    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
briefcase-template/.github/workflows/ci.yml:    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
```

They should have write access as well so they can adjust tags for the `main` branch as appropriate.

**Comment by rmartin16** [comment]
> Also - how on earth do you navigate to the packages list without the magic URL in the ticket? I can see a bunch of Github documentation that says "just click on the `Packages` link"... but damned if I can find that link anywhere - it's definitely not where the screenshots say it is.

Packages are a org level thing so I always get there from https://github.com/beeware and clicking the Packages tab.

**Comment by freakboy3742** [comment]
Ok - I've pruned the list to just those ones (plus toga and briefcase itself, and the support testbed, since those *could* use the build verify step), and set permission to WRITE. Are you able to view those permissions to prove I've done it right? Anything else we can/should do before closing this ticket?

**Comment by rmartin16** [comment]
No; I can't access the settings for a package for beeware.

I did restart the latest CI for Briefcase and it succeeded both in pulling and pushing the images now.

https://github.com/beeware/briefcase/actions/runs/8034160126/job/21946535159#step:21:75

I think we can close for now and monitor CI for any other issues.

**Comment by rmartin16** [comment]
I will say that re-run of CI is logging in to ghcr.io as you so it doesn't test what happens when a non-member initiates CI.

I'll try creating a PR with a non-beeware member account to see if these permissions work for them too.

**Comment by rmartin16** [comment]
Tested the two PRs below:
- https://github.com/beeware/briefcase/pull/1667
- https://github.com/beeware/briefcase/pull/1668

Both were able to pull the package and neither we're able to push the package; this is most likely because the `GITHUB_TOKEN` is not given `write` permissions for PRs from forks.

Closing now since PRs can use the caching images now.

**Comment by rmartin16** [comment]
FWIW, we can finally see some tags for PRs for all the dependabot PRs today.
![image](https://github.com/beeware/.github/assets/387848/7e1bd62c-9d14-4727-9a26-45e8a36c183b)
