### ISSUE TITLE
Upgrade to `actions/upload-artifact@4.0.0` and `actions/download-artifact@4.0.0`

### ISSUE THREAD

**Issue by freakboy3742** [beeware/.github#77]
### What is the problem or limitation you are having?

The v4 releases of `actions/upload-artifact` and `actions/download-artifact` include a series of *massive* backwards incompatibilities:

* It is no longer possible to upload multiple artefacts with the same name
* It is no longer possible to download multiple artefacts with a wildcard (unconfirmed, but definitely not documnted) 
* If you download multiple artefacts, they are now put into parallel subdirectories, instead of being merged into a single directory.

### Describe the solution you'd like

Make the changes necessary to track the new releases. 

### Describe alternatives you've considered

* Stay on the v3 series forever. This will eventually cause bitrot, because the underlying Node version will be deprecated.
* Fork the packages... 

### Additional context

[Github issue requesting guidance on migration](https://github.com/actions/upload-artifact/issues/472)

The following Dependabot PRs were created automatically, and failed CI:
* https://github.com/beeware/.github/pull/75
* https://github.com/beeware/.github/pull/76
* https://github.com/beeware/briefcase/pull/1577
* https://github.com/beeware/briefcase/pull/1578
* https://github.com/beeware/rubicon-objc/pull/394
* https://github.com/beeware/travertino/pull/119
* https://github.com/beeware/toga/pull/2285
* https://github.com/beeware/toga/pull/2286
* https://github.com/beeware/toga-chart/pull/73

The following Dependabot PRs were created automatically, and *passed* CI:
* https://github.com/beeware/cpython-apple-source-deps/pull/2
* https://github.com/beeware/cpython-apple-source-deps/pull/3
* https://github.com/beeware/Python-Apple-support/pull/195
* https://github.com/beeware/Python-Apple-support/pull/196
* https://github.com/beeware/Python-support-testbed/pull/52
* https://github.com/beeware/briefcase-macOS-app-template/pull/31
* https://github.com/beeware/briefcase-macOS-app-template/pull/32
* https://github.com/beeware/briefcase-windows-app-template/pull/28
* https://github.com/beeware/briefcase-windows-app-template/pull/29

Even though they passed CI, Dependabot was suspended for the upload/download actions. It's possible they've worked as intended; but given the size of the change, they usage needs to be carefully audited.

**Comment by rmartin16** [comment]
While the situation has [improved](https://github.com/actions/upload-artifact/issues/472#issuecomment-1861571655) for using the latest version of these actions, after experimenting with them a bit for a separate project, the downloading of artifacts seems much more finicky now. I have seen much higher rates of failures for downloads than with the previous version; most seem to be of the nature of a timeout.

So, while anecdotal, we'll probably be best served by letting these new GitHub services mature a bit more.

**Comment by rmartin16** [comment]
Additionally, because the previous and new versions are not compatible with each other in at least one important operating mode, the upgrade will likely require several co-dependent PRs to rollout the updates to use the new versions across the repos.

**Comment by rmartin16** [comment]
FWIW, more anecdotes about timeouts (which I'm also still seeing in a daily workflow I set up):
- https://github.com/actions/upload-artifact/issues/472#issuecomment-1870204060
- https://github.com/orgs/community/discussions/81413
- Probably most relevant --> https://github.com/actions/download-artifact/issues/249

**Comment by rmartin16** [comment]
I went ahead and did the work to upgrade to v4; whether you want to merge this now or later is up to you. There are still the request timeouts for the `download-artifact` action....but they _seem_ like they may be occurring less often.

In general, the upgrades are rather straightforward; for the repos where the Dependabot PR succeeded, these new PRs can be merged independently and whenever. Although, I wasn't sure how to test any of them...

As for the repos where the Dependabot PRs failed, these new PRs will all need to be merged in tandem with beeware/.github#78.

The one peculiar bit is the output `artifact-name` from the `python-package-create` workflow; it required a non-obvious change for Toga so definitely evaluate if you agree with my change.
